set nocompatible
filetype off

if exists('py2') && has('python')
elseif has('python3')
endif

set rtp+=~/.vim/bundle/Vundle.vim/

call vundle#rc()
" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" Generic
Plugin 'scrooloose/nerdtree'            " File browser
Plugin 'kien/ctrlp.vim'                 " Working with buffers
Plugin 'majutsushi/tagbar'              " Class/module browser (Ctags required)

" Status line
Plugin 'bling/vim-airline'              " Lean & mean status/tabline for vim
Plugin 'vim-airline/vim-airline-themes' " ---dependencies
Plugin 'morhetz/gruvbox'                " Colorscheme

" Completion & snippets
Plugin 'Valloric/YouCompleteMe'
Plugin 'tpope/vim-surround'             " Parentheses, brackets, quotes, XML tags, and more
Plugin 'tpope/vim-commentary'           " Comment stuff out

" Git
Plugin 'fugitive.vim'
Plugin 'airblade/vim-gitgutter'

" Scala
Plugin 'derekwyatt/vim-scala'           " Scala plugin

" Python
Plugin 'klen/python-mode'               " Vim python-mode. PyLint, Rope, Pydoc, breakpoints from box

" CSV
Plugin 'csv.vim'                        " CSV plugin

" Other
Plugin 'wesQ3/vim-windowswap'           " Swapping windows
call vundle#end()

filetype on
filetype plugin on
filetype plugin indent on
syntax on

" General
set visualbell t_vb=            " turn off error beep/flash
set novisualbell                " turn off visual bell
set ls=2                        " always show status bar
set incsearch                   " incremental search
set hlsearch                    " highlighted search results
set nu                          " line numbers
set scrolloff=5                 " keep some more lines for scope
set showmatch                   " show matching brackets/parenthesis
set matchtime=0                 " don't blink when matching
set showmode                    " show current mode down the bottom
set smarttab                    " set smarttab
set encoding=utf-8              " utf-8 default encoding
"set clipboard=unnamedplus       " use system clipboard
set clipboard=unnamed
set backspace=indent,eol,start
set mousemodel=popup
set ruler
set completeopt-=preview
set gcr=a:blinkon0
set ttyfast
set switchbuf=useopen
set t_Co=256
set laststatus=2
set foldmethod=syntax

" Menus
aunmenu Help. 
aunmenu Window.
let no_buffers_menu=1
set wildmenu                    " customize the wildmenu
set wildignore+=*.dll,*.o,*.pyc,*.bak,*.exe,*.jpg,*.jpeg,*.png,*.gif,*$py.class,*.class
set wildmode=list:full

" Scrolling
set scrolloff=4
set sidescrolloff=15
set sidescroll=1

" Backup and swap
set nobackup                    " no backup file
set nowritebackup               " no backup file while editing
set noswapfile                  " no swap file

" Hide panels
"set guioptions-=m              " menu
set guioptions-=T               " toolbar
"set guioptions-=r              " scrollbar

" Wrapping
set nowrap                      " no line wraps
set linebreak                   " wrap lines at convenient points

" Folding
set foldmethod=indent           " fold based on indent
set foldnestmax=3               " deepest fold is 3 levels
set nofoldenable                " dont fold by default

" Mappings
let mapleader=","
nnoremap <leader><space> :noh<cr>   " Clear search highlighting

" Buffers
noremap <S-q> :bd<CR>
noremap <C-Right> :bn<CR>
noremap <C-Left> :bp<CR>

" Tabs
nnoremap <C-S-tab> :tabprevious<CR>
nnoremap <C-tab>   :tabnext<CR>
nnoremap <C-t>     :tabnew<CR>
inoremap <C-S-tab> <Esc>:tabprevious<CR>i
inoremap <C-tab>   <Esc>:tabnext<CR>i
inoremap <C-t>     <Esc>:tabnew<CR>

" Split navigations
nnoremap <C-j> <C-w><C-j>
nnoremap <C-k> <C-w><C-k>
nnoremap <C-l> <C-w><C-l>
nnoremap <C-h> <C-w><C-h>

" Change size for splitted windows
" nnoremap <S-[> :vertical resize +5<cr>
" nnoremap <S-]> :vertical resize -5<cr>

" changing between syntaxes
nnoremap <leader>Tp :set ft=python<CR>
nnoremap <leader>Tj :set ft=java<CR>
nnoremap <leader>Ts :set ft=scala<CR>
nnoremap <leader>Tc :set ft=cs<CR>

" autocomplete
inoremap <C-space> <C-x><C-o>

"----Plugins----
" NERDtree
let g:NERDTreeDirArrows=0
let NERDTreeShowHidden=1
"-- for win
"-- let g:NERDTreeDirArrowExpandable = '>'
"-- let g:NERDTreeDirArrowCollapsible = '*'
let NERDTreeIgnore=['\~$', '\.pyc$', '\.pyo$', '\.class$', 'pip-log\.txt$', '\.o$']
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
nmap <leader>n :NERDTreeToggle<cr>

" Paste mode
nnoremap <F2> :set invpaste paste?<CR>
set pastetoggle=<F2>
set showmode

" TagBar 
let g:tagbar_autofocus = 1
" set tags=$HOME/tags
map <F4> :TagbarToggle<CR>


" Youcompleteme
let g:ycm_server_log_level = 'debug'
let g:ycm_server_use_vim_stdout = 1
let g:ycm_confirm_extra_conf=0

" Python Mode
let g:pymode_python = 'python3'
let g:pymode_rope = 1
let g:pymode_lint = 1
" let g:pymode_lint_checkers = ['pylint', 'pep8', 'mccabe', 'pep257', 'pyflakes']
" let g:pymode_lint_checkers = ['pep8']
let g:pymode_lint_ignore="E501,W601"

"----Git
" Gitgutter
nmap <Leader>hs <Plug>GitGutterStageHunk
nmap <Leader>hu <Plug>GitGutterUndoHunk

" Encoding menu
set wcm=<Tab>
menu Encoding.koi8-r :e ++enc=koi8-r ++ff=unix<CR>
menu Encoding.windows-1251 :e ++enc=cp1251 ++ff=dos<CR>
menu Encoding.cp866 :e ++enc=cp866 ++ff=dos<CR>
menu Encoding.utf-8 :e ++enc=utf8 <CR>
menu Encoding.koi8-u :e ++enc=koi8-u ++ff=unix<CR>
map <F8> :emenu Encoding.<TAB>

" Ctrl-P
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'
let g:ctrlp_working_path_mode = 'ra'
let g:ctrlp_show_hidden = 1
let g:ctrlp_max_files = 600
let g:ctrlp_max_depth = 6
let g:ctrlp_working_path_mode = 1
nnoremap <leader>. :CtrlPTag<cr>

" Vim-Airline
colorscheme gruvbox 
set background=dark
let g:airline_theme='gruvbox'
" let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#formatter = 'unique_tail'
